[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['npx prisma generate']

[start]
cmd = 'npm run bot'
