[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm run start'
