# Railway nixpacks конфигурация
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = ['npm install', 'npx prisma generate']

[phases.build] 
cmds = ['npm run build']

[start]
cmd = 'npm run start'
